language: node_js
node_js:
  - 'lts/*'
install:
  - npm install
jobs:
  include:
    - stage: Test
      env:
        global:
          - NODE_ENV=development
      script:
        - npm test
    - stage: npm release
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - /^v[0-9]+.*$/
